FROM registry.ci.openshift.org/ocp/4.16:must-gather
# to make SAST/SNYK happy
RUN rm -rf examples
RUN rm -f vendor/k8s.io/apimachinery/pkg/util/managedfields/pod.yaml
COPY must-gather/* /usr/bin/
RUN chmod +x /usr/bin/gather

ENTRYPOINT /usr/bin/gather
