FROM registry.ci.openshift.org/ocp/4.10:must-gather AS builder
WORKDIR /go/src/github.com/openshift/csi-driver-shared-resource
COPY . .

FROM registry.ci.openshift.org/ocp/4.10:cli
COPY --from=builder /go/src/github.com/openshift/csi-driver-shared-resource/must-gather/* /usr/bin/
RUN chmod +x /usr/bin/gather

ENTRYPOINT /usr/bin/gather