# RBAC required by the shared resource CSI driver node plugin and its metrics.
# Sourced from https://github.com/openshift/csi-driver-shared-resource-operator/tree/master/assets/rbac
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - node_role.yaml
  - node_binding.yaml
  - privileged_role.yaml
  - node_privileged_binding.yaml
  - prometheus_role.yaml
  - prometheus_rolebinding.yaml
