apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shared-resource-csi-driver-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shared-resource-csi-driver-node
subjects:
  - kind: ServiceAccount
    name: shared-resource-csi-driver-node
    namespace: openshift-cluster-csi-drivers