# Service defined here, plus serviceName below in DaemonSet,
# are needed only because of condition explained in
# https://github.com/kubernetes/kubernetes/issues/69608

kind: Service
apiVersion: v1
metadata:
  name: csi-hostpathplugin
  namespace: openshift-cluster-csi-drivers
  labels:
    app: csi-hostpathplugin
spec:
  selector:
    app: csi-hostpathplugin
  ports:
    - name: dummy
      port: 12345
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-hostpathplugin
  namespace: openshift-cluster-csi-drivers
  labels:
    app: csi-hostpathplugin
spec:
  selector:
    matchLabels:
      app: csi-hostpathplugin
  template:
    metadata:
      labels:
        app: csi-hostpathplugin
    spec:
      serviceAccountName: csi-driver-shared-resource-plugin
      containers:
        - name: node-driver-registrar
          image: quay.io/openshift/origin-csi-node-driver-registrar:4.8.0
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-hostpath/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
            - mountPath: /csi-data-dir
              name: csi-data-dir

        - name: hostpath
          image: quay.io/openshift/origin-csi-driver-shared-resource:4.9.0
          # for development purposes; eventually switch to IfNotPresent
          imagePullPolicy: Always
          command:
            - csi-driver-shared-resource
          args:
            - "--drivername=csi.shared-resources.openshift.io"
            - "--v=4"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - --ignorenamespace=openshift-machine-api
            - --ignorenamespace=openshift-kube-apiserver
            - --ignorenamespace=openshift-kube-apiserver-operator
            - --ignorenamespace=openshift-kube-scheduler
            - --ignorenamespace=openshift-kube-controller-manager
            - --ignorenamespace=openshift-kube-controller-manager-operator
            - --ignorenamespace=openshift-kube-scheduler-operator
            - --ignorenamespace=openshift-console-operator
            - --ignorenamespace=openshift-controller-manager
            - --ignorenamespace=openshift-controller-manager-operator
            - --ignorenamespace=openshift-cloud-credential-operator
            - --ignorenamespace=openshift-authentication-operator
            - --ignorenamespace=openshift-service-ca
            - --ignorenamespace=openshift-kube-storage-version-migrator-operator
            - --ignorenamespace=openshift-config-operator
            - --ignorenamespace=openshift-etcd-operator
            - --ignorenamespace=openshift-apiserver-operator
            - --ignorenamespace=openshift-cluster-csi-drivers
            - --ignorenamespace=openshift-cluster-storage-operator
            - --ignorenamespace=openshift-cluster-version
            - --ignorenamespace=openshift-image-registry
            - --ignorenamespace=openshift-machine-config-operator
            - --ignorenamespace=openshift-sdn
            - --ignorenamespace=openshift-service-ca-operator
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          ports:
          - containerPort: 9898
            name: healthz
            protocol: TCP
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /var/lib/kubelet/plugins
              mountPropagation: Bidirectional
              name: plugins-dir
            - mountPath: /csi-data-dir
              name: csi-data-dir
            - mountPath: /csi-volumes-map
              name: csi-volumes-map
            - mountPath: /dev
              name: dev-dir

      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-hostpath
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
        - hostPath:
            path: /var/lib/kubelet/plugins
            type: Directory
          name: plugins-dir
        - hostPath:
            path: /var/lib/csi-volumes-map/
            type: DirectoryOrCreate
          name: csi-volumes-map
        - emptyDir:
            # this tells Kubernetes to mount a tmpfs (RAM-backed filesystem)
            medium: Memory
          name: csi-data-dir
        - hostPath:
            path: /dev
            type: Directory
          name: dev-dir
